apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: devops-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-server
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:
      securityContext:
            fsGroup: 1000 
            runAsUser: 1000
      serviceAccountName: jenkins-admin
      initContainers:
        - name: install-docker
          image: docker:stable
          command: ["cp", "/usr/local/bin/docker", "/data/docker"]
          volumeMounts:
            - mountPath: "/data"
              name: docker
        - name: install-kubectl
          image: gcr.io/mostafa-salah-377213/install-kubectl
          command: ["cp", "/usr/local/bin/kubectl", "/data/kubectl" ]
          volumeMounts:
          - name: kubectl
            mountPath: "/data"
            
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          securityContext:
             allowPrivilegeEscalation: false
             runAsUser: 0
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - name: httpport
              containerPort: 8080
            - name: jnlpport
              containerPort: 50000
          livenessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home  
            - name: docker-sock
              mountPath: /var/run
            - name: "docker"
              subPath: "docker"
              mountPath: "/usr/local/bin/docker"
            - name: "kubectl"
              subPath: "kubectl"
              mountPath: "/usr/local/bin/kubectl"
          
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
              claimName: jenkins-pv-claim
        - name: docker
          emptyDir: {}
        - hostPath:
            path: /var/run
            type: ""
          name: docker-sock
        - name: kubectl
          emptyDir: {}